### ISSUE TITLE
Learning Site Advices

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson-Learning-Extension#7]
Hello,

I want to create learning site. The extension enough for basic but not complete solution. I want to user account system and record the user activities, passed exams, taked courses etc.

So do you know any other extensions for the system maybe good works with Unyson, or should i code my own solution top of the Unyson. What do you think?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/874

**Comment by moldcraft** [comment]
Try our Learning extension, if it will not fit your needs, find a plugin for that.
