### ISSUE TITLE
Ajax for Quizes

### ISSUE THREAD

**Issue by Priler** [ThemeFuse/Unyson-Learning-Extension#8]
Hi!

Is there a way to make Quizes to be Ajax?

**Comment by moldcraft** [comment]
If the form handled by the `FW_Form` helper, you can try [this solution](http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit)

**Comment by Priler** [comment]
Seems like it handled with FW_Form, but this not works.

**Comment by Priler** [comment]
This error in console ```2fw-form-helpers.js:41 Uncaught TypeError: Cannot read property 'errors' of undefined```

**Comment by Priler** [comment]
For some reason ajax request always return 0 in Network tab.
How this can be fixed?

**Comment by moldcraft** [comment]
The form is registered [here](https://github.com/ThemeFuse/Unyson-Learning-Extension/blob/2429d609a4c5190b51cb1eb0c9d2163613326ac6/extensions/learning-quiz/class-fw-extension-learning-quiz.php#L335) on [this action](https://github.com/ThemeFuse/Unyson-Learning-Extension/blob/2429d609a4c5190b51cb1eb0c9d2163613326ac6/extensions/learning-quiz/class-fw-extension-learning-quiz.php#L636). Maybe that action is executed later than `wp_ajax_*` action

**Comment by Priler** [comment]
@moldcraft How it may be fixed?

**Comment by moldcraft** [comment]
```js
jQuery(function($){
    var selector = 'form[data-fw-form-id="learning-quiz-quiz-form"]';

    $(document.body).on('submit', selector, function(e){
        e.preventDefault();
    
        var $form = jQuery(this);
        
        // get submit button
		{
			var $submitButton = $form.find(':submit:focus');

			if (!$submitButton.length) {
				// in case you use this solution http://stackoverflow.com/a/5721762
				$submitButton = $form.find('[clicked]:submit');
			}

			// make sure to remove the "clicked" attribute to prevent accidental settings reset
			$form.find('[clicked]:submit').removeAttr('clicked');
		}
		
		jQuery.ajax({
			type: "POST",
			url: $form.attr('action'),
			data: $form.serialize() + ($submitButton.length ? '&'+ $submitButton.attr('name') +'='+ $submitButton.attr('value') : ''),
			dataType: 'html'
		})
		    .done(function(html){ window.hhh = html;
				$form.closest('.fw-learning-quiz').html(
				    $('.fw-learning-quiz', html).html()
				);
			}).fail(function(jqXHR, textStatus, errorThrown){
				alert(String(errorThrown));
			});
    });
});
```
