### ISSUE TITLE
only visual builder is available in lesson post

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Learning-Extension#9]
When I add a new lesson post: https://static.md/0a7970284b4c423e06f0b441c78237ae.png , only the visual page builder is available, the default editor dissaperead

**Comment by andronic90** [comment]
also the publish/update button is not displayed in the right sidebar

**Comment by andreiglingeanu** [comment]
Is this still a problem? I think recently I was messing around with `editor_integration.js` and it may've been solved it.

**Comment by moldcraft** [comment]
I tested it yesterday.
